const sdata = [
  {
    sdfname: "Aguli",
    sdlname: "Agladze",
    sdamt: "2750",
    sdamtoutof: "4000",
    // sdprogval: `${Math.round((sdamt / sdamtoutof) * 100)}`,
  },
  {
    sdfname: "Amiran",
    sdlname: "Asaratasvali",
    sdamt: "980",
    sdamtoutof: "5000",
  },
  {
    sdfname: "Andria",
    sdlname: "Abashidze",
    sdamt: "2875",
    sdamtoutof: "9500",
  },
  {
    sdfname: "Aleko",
    sdlname: "Alikhanashivli",
    sdamt: "450",
    sdamtoutof: "750",
  },
  {
    sdfname: "Aleko",
    sdlname: "Alikhanashivli",
    sdamt: "450",
    sdamtoutof: "750",
  },
  {
    sdfname: "Aleko",
    sdlname: "Alikhanashivli",
    sdamt: "450",
    sdamtoutof: "750",
  },
  {
    sdfname: "Aleko",
    sdlname: "Alikhanashivli",
    sdamt: "450",
    sdamtoutof: "750",
  },
  {
    sdfname: "Binod",
    sdlname: "shivli",
    sdamt: "850",
    sdamtoutof: "2000",
  },
  {
    sdfname: "Bani",
    sdlname: "shivli",
    sdamt: "350",
    sdamtoutof: "800",
  },
  {
    sdfname: "Bina",
    sdlname: "Sangam",
    sdamt: "550",
    sdamtoutof: "660",
  },
  {
    sdfname: "Bhushra",
    sdlname: "shivli",
    sdamt: "100",
    sdamtoutof: "720",
  },
  {
    sdfname: "Barbie",
    sdlname: "shivli",
    sdamt: "455",
    sdamtoutof: "650",
  },
  {
    sdfname: "Babita",
    sdlname: "shivli",
    sdamt: "430",
    sdamtoutof: "600",
  },
  {
    sdfname: "Bimal",
    sdlname: "khanna",
    sdamt: "850",
    sdamtoutof: "930",
  },
  {
    sdfname: "cniila",
    sdlname: "Arnavlli",
    sdamt: "955",
    sdamtoutof: "6660",
  },
  {
    sdfname: "Cyclone",
    sdlname: "gangotri",
    sdamt: "550",
    sdamtoutof: "5230",
  },
  {
    sdfname: "Cylender",
    sdlname: "Arnavlli",
    sdamt: "766",
    sdamtoutof: "6900",
  },
  {
    sdfname: "Camelo",
    sdlname: "Arnavlli",
    sdamt: "930",
    sdamtoutof: "7520",
  },
  {
    sdfname: "Cfx",
    sdlname: "vllie",
    sdamt: "900",
    sdamtoutof: "6500",
  },
  {
    sdfname: "cinema",
    sdlname: "Arnavlli",
    sdamt: "750",
    sdamtoutof: "6530",
  },
  {
    sdfname: "Cute",
    sdlname: "Arival",
    sdamt: "260",
    sdamtoutof: "6500",
  },
  {
    sdfname: "Doggy",
    sdlname: "Arival",
    sdamt: "2699",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Desuza",
    sdlname: "Arival",
    sdamt: "3599",
    sdamtoutof: "9600",
  },
  {
    sdfname: "Demo",
    sdlname: "valleo",
    sdamt: "2859",
    sdamtoutof: "6500",
  },
  {
    sdfname: "Disha",
    sdlname: "Arival",
    sdamt: "2699",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Devika",
    sdlname: "Arival",
    sdamt: "699",
    sdamtoutof: "9500",
  },
  {
    sdfname: "Danish",
    sdlname: "zyan",
    sdamt: "699",
    sdamtoutof: "8360",
  },
  {
    sdfname: "Doggy",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
  {
    sdfname: "Eiile",
    sdlname: "lamo",
    sdamt: "529",
    sdamtoutof: "8500",
  },
];
export default sdata;
